### ISSUE TITLE
error using SDE, randomizer, ValueError: expected non-negative integer

### ISSUE THREAD

**Issue by eugenioamato** [SethRobinson/aitools_client#11]
Steps to reproduce
1- select "DPM++ SDE Karras" or ""DPM++ SDE" as sampler
2- generate a new image

Expected result:
An image is generated

Error:
500 internal error
(Happens randomly, not always, 50% times)
note:
I am unable to see the file in the repo that sends this random number generation, I don't know Unity 

```
API error: POST: http://localhost:7860/sdapi/v1/txt2img {'error': 'ValueError', 'detail': '', 'body': '', 'errors': 'expected non-negative integer'}
Traceback (most recent call last):
  File "C:\code\sd.webui\system\python\lib\site-packages\anyio\streams\memory.py", line 94, in receive
    return self.receive_nowait()
  File "C:\code\sd.webui\system\python\lib\site-packages\anyio\streams\memory.py", line 89, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\code\sd.webui\system\python\lib\site-packages\starlette\middleware\base.py", line 78, in call_next
    message = await recv_stream.receive()
  File "C:\code\sd.webui\system\python\lib\site-packages\anyio\streams\memory.py", line 114, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\code\sd.webui\webui\modules\api\api.py", line 144, in exception_handling
    return await call_next(request)
  File "C:\code\sd.webui\system\python\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
    raise app_exc
  File "C:\code\sd.webui\system\python\lib\site-packages\starlette\middleware\base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\code\sd.webui\system\python\lib\site-packages\starlette\middleware\base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
  File "C:\code\sd.webui\webui\modules\api\api.py", line 109, in log_and_time
    res: Response = await call_next(req)
  File "C:\code\sd.webui\system\python\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
    raise app_exc
  File "C:\code\sd.webui\system\python\lib\site-packages\starlette\middleware\base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\code\sd.webui\system\python\lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "C:\code\sd.webui\system\python\lib\site-packages\starlette\middleware\gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "C:\code\sd.webui\system\python\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\code\sd.webui\system\python\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\code\sd.webui\system\python\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\code\sd.webui\system\python\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\code\sd.webui\system\python\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\code\sd.webui\system\python\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\code\sd.webui\system\python\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "C:\code\sd.webui\system\python\lib\site-packages\fastapi\routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "C:\code\sd.webui\system\python\lib\site-packages\fastapi\routing.py", line 165, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "C:\code\sd.webui\system\python\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "C:\code\sd.webui\system\python\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\code\sd.webui\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\code\sd.webui\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\code\sd.webui\webui\modules\api\api.py", line 318, in text2imgapi
    processed = process_images(p)
  File "C:\code\sd.webui\webui\modules\processing.py", line 526, in process_images
    res = process_images_inner(p)
  File "C:\code\sd.webui\webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 42, in processing_process_images_hijack
    return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
  File "C:\code\sd.webui\webui\modules\processing.py", line 680, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "C:\code\sd.webui\webui\modules\processing.py", line 907, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "C:\code\sd.webui\webui\modules\sd_samplers_kdiffusion.py", line 373, in sample
    noise_sampler = self.create_noise_sampler(x, sigmas, p)
  File "C:\code\sd.webui\webui\modules\sd_samplers_kdiffusion.py", line 311, in create_noise_sampler
    return BrownianTreeNoiseSampler(x, sigma_min, sigma_max, seed=current_iter_seeds)
  File "C:\code\sd.webui\webui\repositories\k-diffusion\k_diffusion\sampling.py", line 110, in __init__
    self.tree = BatchedBrownianTree(x, t0, t1, seed)
  File "C:\code\sd.webui\webui\repositories\k-diffusion\k_diffusion\sampling.py", line 80, in __init__
    self.trees = [torchsde.BrownianTree(t0, w0, t1, entropy=s, **kwargs) for s in seed]
  File "C:\code\sd.webui\webui\repositories\k-diffusion\k_diffusion\sampling.py", line 80, in <listcomp>
    self.trees = [torchsde.BrownianTree(t0, w0, t1, entropy=s, **kwargs) for s in seed]
  File "C:\code\sd.webui\system\python\lib\site-packages\torchsde\_brownian\derived.py", line 155, in __init__
    self._interval = brownian_interval.BrownianInterval(t0=t0,
  File "C:\code\sd.webui\system\python\lib\site-packages\torchsde\_brownian\brownian_interval.py", line 537, in __init__
    generator = np.random.SeedSequence(entropy=entropy, pool_size=pool_size)
  File "bit_generator.pyx", line 307, in numpy.random.bit_generator.SeedSequence.__init__
  File "bit_generator.pyx", line 381, in numpy.random.bit_generator.SeedSequence.get_assembled_entropy
  File "bit_generator.pyx", line 138, in numpy.random.bit_generator._coerce_to_uint32_array
  File "bit_generator.pyx", line 68, in numpy.random.bit_generator._int_to_uint32_array
ValueError: expected non-negative integer


```

**Comment by SethRobinson** [comment]
Thanks, can verify that this happens to me too (using the latest version of auto1111 as of yesterday) - can confirm that non-random seeds (anything besides -1 as the seed) do not give errors, but of course the image will always be the same (even with 0).

-1 is the correct parm for random, so I suspect this is an error is not on my side of things (most settings accept -1 fine in the auto1111 API), but can't be positive right now.

**Comment by eugenioamato** [comment]
I guess it can be done like this?
aitools_client\Assets\_Script\Pic\PicInpaint.cs

                 VVVVVVV                          V
m_seed = Math.Abs(rand.NextLong());

**Comment by SethRobinson** [comment]
This has been fixed in the latest build, thanks!
